version: '2'
services:
  app1:
    image: app1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8081:8080"
  app2:
    image: app2
    build: .
    container_name: backend1
    ports:
      - "8082:8080"
  app3:
    image: app3
    build:
      context: .
      dockerfile: Dockerfile-second
    container_name: backend3
    ports:
      - "8083:8080"

